### ISSUE TITLE
Update outlier detection

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#101]
It has been ~5 years since the reverse jacknife outlier detection was implemented by Simon Bennett (retired from DoEE). Since then, we have had many updates of the environmental layers and the addition of new tools (e.g., AOO/EOO) that should help. This issue is a marker to ensure we consider updating the tests. Outlier tests are not part of the CORE TDWG Task Group 2 tests/assertions (as they can be non-trivial to implement and can be contentious. 

Developer time: 3 days
Research/admin time:  3 days

**Comment by nickdos** [comment]
**If** we are going to update the code for this (as well as look at utilising better layers), then @djtfmartin should be involved as it might be worth implementing a module for the GBIF shared processing code base(?) at some point.

**Comment by Tasilee** [comment]
Fully agree. I will also be discussing this with Ben Raymond tomorrow. 

Also FYI: Outlier tests were put outside (sic.) the TDWG Data Quality Task Group 2 (Tests and assertions):  https://github.com/tdwg/bdq/issues because they didn't meet the criteria for inclusion.

**Comment by Tasilee** [comment]
Discussed with Adam as one option would be to use multivariates (e.g., say 10-30 layers) holistically with say an alpha hull, rather than multiple univariate tests say as reverse jacknife. Dependent on a) implemented alpha hull option in AOO/EOO tool and b) updated layers

Any updates with be dependent on improved climatic layers (250m from Kristen WIlliams) and BioOracle and MERAclim marine layers.
