### ISSUE TITLE
Add count of MERIT and BioCollect polygons intersecting with Area Reports

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#105]
| Field | Value |
| ----- | ----- |
| **Type** | Enhancement  |
| **Priority** | 7 |
| **Sprint** | 2 | 
| **Developer days** | 2 |
| **Admin days** | 0 |
| **Description** | Polygons from MERIT and BioCollect projects are available and should be reported  in Area Reports |
| **Epic** |  Efficient ecological analysis |
| **Theme Links** | Community data collection |
| **Community** | Research, management |

**Comment by Tasilee** [comment]
We used to have a POI (Points of Interest) component in the Tools | Area reports but this was lost. Given that all of the bioCollect and MERIT projects have a defined polygonal boundary, it is important to be able to locate any such projects within any user-defined area.

This is a perfect example of the need to ensure that ALA data is cross-linked wherever possible. While projects can be searched for by name from BioCollect and MERIT, the ability to search for projects by area is not. The Spatial Portal's area reports are aimed at informing users of all bio-related data within a user-defined area. Knowing that there are or were bio/management projects operating in an area is a significant dimension of practical information.

**Comment by Tasilee** [comment]
We would ideally add two more 'records' one for MERIT projects and one for BioCollect projects, with the number listed linked to table with project metadata with link to project details.

**Comment by Tasilee** [comment]
Adam and I have discussed this and we believe the following would add massive value to both Projects and reporting on areas. Exposure of AREAs of projects in two places-

1. Gazetteer polygon (Add to Map | Area | Gazetteer polygon - where name of polygon or Project can be found and mapped.
1. Area report - add an entry that is called "Projects" which lists the number of projects from MERIT/BioCollect that have an area which intersects with the target area.  The Projects can be LISTED (maybe project name, project type with link to more details in MERIT/BioCollect) or MAPPED to map the project areas.

**Comment by qifeng-bai** [comment]
See implementations : https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/3
