### ISSUE TITLE
Unable to update field name due to rollback exception

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#11]
I discovered that when creating a field name yesterday I had forgotten to include part of the name, so I went to update it this morning. However, it is consistently giving me a rollback exception and not updating the name:

<img width="1124" alt="screen shot 2016-06-21 at 8 47 21 am" src="https://cloud.githubusercontent.com/assets/82365/16212713/fe2aff94-378c-11e6-8402-de44acf13052.png">

The following field needs to have its name changed to match its description:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10856

**Comment by adam-collins** [comment]
Field names on staging can now be changed.
