### ISSUE TITLE
Occurrence density and species richness layers from Point to grid available for analyses

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#111]
Like any other layer produced in the Spatial Portal, Occurrence density and Species richness layers (optionally) from 'Tools | Point to grid' should be available for use in subsequent analyses, e.g., Prediction, Classification, Export | Points, Scatterplot etc.

**Comment by javier-molina** [comment]
It comes from https://support.ehelp.edu.au/a/tickets/25198

**Comment by Tasilee** [comment]
This issue still applies more than ever.
