### ISSUE TITLE
1 million queries to sandbox over a hour long periods

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#127]
When sandbox fails to respond or errors on a query from this broken code:

https://github.com/AtlasOfLivingAustralia/spatial-service/blob/cad8882b17ac94642c5204a355b70738e149c991/src/main/groovy/au/org/ala/spatial/process/GeneratePoints.groovy#L77-L87

there are 1 million queries executed over the next 1 hour to `aws-sandbox`. These are flooding both the `aws-sandbox` log files, and our log aggregation system.

This needs to urgently be fixed!

**Comment by adam-collins** [comment]
Fixed on prod.
