### ISSUE TITLE
Exporting maps from portal not yet implemented

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#13]
Exporting maps from the portal is not yet implemented, and when chosen shows a blank dialog box as shown below:

<img width="719" alt="screen shot 2016-06-24 at 11 20 50 am" src="https://cloud.githubusercontent.com/assets/82365/16325047/ca79813e-39fd-11e6-9b7a-8ce1888fdf23.png">

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#17
