### ISSUE TITLE
Shapefile upload not working with Point geometry

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-service#130]
To reproduce:
1) Upload shapefile containing Points via the webservice /ws/shape/upload/shp
2) Create an object from the shapefile /ws/shape/upload/shp/shapefile id/object id

Actual result:
```
Error processsing shapefile feature request
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object
 'POINT (147.11694208903975 -35.43225945957232)' with class 'com.vividsolutions.jts.geom.Point' to class 'com.vividsolutions.jts.geom.GeometryCollection'
...
at au.org.ala.spatial.slave.SpatialUtils.getShapeFileFeaturesAsWkt(SpatialUtils.groovy:525)
..
```

**Comment by ansell** [comment]
All of the shapefiles that I upload use `POLYGON` or `MULTIPOLYGON` so `POINT` wasn't tested by my use cases.

**Comment by adam-collins** [comment]
This now works for my test shapefile containing points.
