### ISSUE TITLE
layers.json is returning 404

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-service#132]
Picked up in `alerts` app log. 

https://spatial.ala.org.au/ws/layers.json = 404 not found
https://spatial.ala.org.au/ws/layers = 200 OK

Fix: https://spatial.ala.org.au/ws/layers.json should resolve to https://spatial.ala.org.au/ws/layers.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/177f9e2ea7907fe524f96d4ac83c429e8394d466
