### ISSUE TITLE
Tasks stopped being processed

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/spatial-service#133]
14/05/2019 tasks weren't being processed by the spatial service.
17 tasks in state 0, none running.

Took a thread dump and backed up the logs in my home directory.  Errors exist in the logs around the time the last task with a non-zero status was handled (~02:47am 14/05/2019) but they didn't appear to indicate the task monitoring thread had finished/died.

Restarting tomcat restarted the task processing.

**Comment by qifeng-bai** [comment]
Fixed
