### ISSUE TITLE
No CORS headers being provided for /ws/distribution/map requests

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-service#135]
See AtlasOfLivingAustralia/bie-plugin/issues/156.

E.g. requests for https://spatial.ala.org.au/ws/distribution/map/urn:lsid:biodiversity.org.au:afd.taxon:0217f06f-664c-4c64-bc59-1b54650fa23d

do not currently provide any `Access-Control-Allow-Origin` or similar headers.

@ansell checked today (2019-06-05) and found:

> Peter Ansell [2:04 PM]
I didn't look into how or whether it was implemented in the end, but the JSON/JSONP URL above doesn't have `Access-Control-Allow-Origin` or the other three CORS headers on it for me when looking at them in the Firefox dev tools

referring to https://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:afd.taxon:0217f06f-664c-4c64-bc59-1b54650fa23d

**Comment by adam-collins** [comment]
This is a CORB issue fixed in bie-plugin with https://github.com/AtlasOfLivingAustralia/bie-plugin/commit/94a7d22b03233abb5e523d4f36c5f38b3ad489f4

**Comment by adam-collins** [comment]
This is now working in prod.
