### ISSUE TITLE
export checklist not working for uploaded kml

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/spatial-service#139]
upload kml file
[Sustainable Farms Region.zip](https://github.com/AtlasOfLivingAustralia/spatial-service/files/3684316/Sustainable.Farms.Region.zip)

add to map, species, "Lepidoptera" for the area
export checklist
just hangs at "Export a species list"  "Loading"

reported by support ticket: https://support.ehelp.edu.au/a/tickets/38494

confirmed in both firefox and chrome

**Comment by Tasilee** [comment]
Reproduced (Export | Area checklist) on KML area.
