### ISSUE TITLE
Import points functionality not yet implemented

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#14]
The Import points functionality has a TODO note in the interface and is unresponsive when clicked on:

<img width="434" alt="screen shot 2016-06-24 at 11 22 26 am" src="https://cloud.githubusercontent.com/assets/82365/16325078/1396018a-39fe-11e6-82e8-196d139603ee.png">

**Comment by adam-collins** [comment]
Moved to AtlasOfLivingAustralia/spatial-hub#7
