### ISSUE TITLE
Deletion of uploaded layers fails

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#149]
1. Go to: `https://nectar-spatial-staging.ala.org.au/ws/manageLayers/uploads`
2. Search for `664` (The `Sodicity` layer)
3. Click on `Delete` next to the `Sodicity` layer
4. Nothing happens. Observe a failure in developer tools related to it:

```
Uncaught ReferenceError: sodicity is not defined
    onclick https://nectar-spatial-staging.ala.org.au/ws/manageLayers/uploads:1
```

The onclick handler in question seems to be:

```
<a onclick="return confirmDelete(sodicity, 'sodicity');" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i> delete</a>
```

**Comment by ansell** [comment]
Testing this deletion on nectar-spatial-test works. Moving this to Waiting for CAB to track it going through CAB and being deployed.

**Comment by adam-collins** [comment]
Fixed in snapshot.
