### ISSUE TITLE
Standardize   login/admin/Apikey security check  with annotations

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-service#155]
Use annotations like @RequireApiKey to process login/role check on Controllers

It should support:

CAS bypass
RequireLogin, RequireAdmin
ApiKey stored in header, params, and body

Todo:
Check if task/output in TaskControl have been removed from "LoginRequired"

**Comment by qifeng-bai** [comment]
PR on Spatial Hub: https://github.com/AtlasOfLivingAustralia/spatial-hub/pull/378
PR on Spatial Service : https://github.com/AtlasOfLivingAustralia/spatial-service/pull/154

**Comment by nickdos** [comment]
@qifeng-bai could you suggest a few SP commands/actions that will trigger/test this issue?

**Comment by qifeng-bai** [comment]
@nickdos   we can run some "uploading process", e.g creating an area from SHP file , or run any tools .  If they runs properly and  don't have authentication related error popped up,  it is safe to say this function works

**Comment by nickdos** [comment]
SHP upload worked as expected. Species list upload also worked.
