### ISSUE TITLE
Downloading single scatterplot data produces nearly empty CSV file

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-service#162]
When running a single scatterplot, then attempting to Download data, the downloaded scatterpotData.csv file is almost empty, containing only the following characters: "PK                  "

The scatterplot appears to run correctly and shows graphs, it's just the download of data that appears not to work.

This only appears to affect single scatterplots when you click the "Download data" button. Running a multiple scatterplot successfully downloads the scatterplot graphs in a zip file. 

Raised in helpdesk ticket 89945.

**Comment by Tasilee** [comment]
Tested (spatial test) and the exported file is not CSV as it not readable by Excel. When viewed it is in a binary format.

**Comment by qifeng-bai** [comment]
ScatterPlot creates a output.download = data.csv,  the value is overwritten in : https://github.com/AtlasOfLivingAustralia/spatial-service/blob/master/grails-app/services/au/org/ala/spatial/service/TasksService.groovy#L256

It finally ends up with downloading 'download.zip'
