### ISSUE TITLE
Cannot display layers on 'Edit Field'

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-service#164]
Select one of available layers, click Map tab -> layer is shown up on the map
However, if click 'field' -> Map,  the layer is not show up on the map

**Comment by nickdos** [comment]
@qifeng-bai please provide a bit more info on how to reproduce/test this issue. E.g. step by step instructions.

**Comment by qifeng-bai** [comment]
@nickdos 

Test:

Go to: https://spatial-test.ala.org.au/ws/.
Click: View available layers
Click the first layer: cl10957: CAPAD 2018 Marine  -> by clicking the link in "Field" column
Click "Map" tab -> Should see the layers

**Comment by nickdos** [comment]
Works now ✅
