### ISSUE TITLE
Downloading species list returns 4 species

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-service#167]
@timhicks-ala  reported: 

I think there's an issue with downloading species lists. I have a square area drawn over Queanbeyan and the area report says 1853 species, and downloading the list from the area report shows them all. However, the link in the quick links box to download the species list produces a file with 4 species listed
9:04
Drawing a box around a much smaller area, where the area report shows 1 species, produces the exact same file with 4 species

**Comment by timhicks-ala** [comment]
Work-around is available by downloading species list via Area report - will provide this work-around to users in the meantime.

Originally reported in https://support.ehelp.edu.au/a/tickets/102533

**Comment by qifeng-bai** [comment]
Suspect  downloading process is broken:

Manually  downloading species list via this link, returns the same result within Area report - 12 species
https://biocache-ws-test.ala.org.au/ws/occurrences/facets/download%3Ffacets=names_and_lsid&lookup=true&count=true&lists=true&q=qid:1615852959956

**Comment by timhicks-ala** [comment]
Testing on spatial-test:
- Created area around a specific location
- Downloaded species list - ~2200 species (this would show 4 species in prod)
- Created area report - reports ~2200 species
Test successful.

**Comment by timhicks-ala** [comment]
Additionally reported in https://support.ehelp.edu.au/a/tickets/104613
