### ISSUE TITLE
Maxent (Predict tool) currently fails to run

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/spatial-service#179]
Fails to run with any parameters.

Reported in https://support.ehelp.edu.au/a/tickets/109633

![image](https://user-images.githubusercontent.com/57081387/122692597-6efecc00-d279-11eb-8389-6d2067d9ebe0.png)

**Comment by qifeng-bai** [comment]
Has been fixed on the release of 17 July 2021

**Comment by nickdos** [comment]
Should that be 14 July, @qifeng-bai ? 17th is 2 days in the fututre...

**Comment by qifeng-bai** [comment]
@nickdos You are right. Updated my comments :)
