### ISSUE TITLE
After successful upload of shapefile, no fields shown in the Source id dropdown list

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#18]
After successfully uploading a layer:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/10858

No fields from the shapefile are shown in the Source id dropdown list when attempting to add a field to the layer:

![screen shot 2016-07-07 at 4 30 05 pm](https://cloud.githubusercontent.com/assets/82365/16644410/2049ff0a-4460-11e6-9d87-c93857d801c8.png)

**Comment by ansell** [comment]
The layer opens correctly for me locally using QGis, PostGIS and Geotools. The expected list of fields is:

* DT_CREATE
* DT_RETIRE
* NAME
* DT_GAZETD
* CE_PLY_PID
* STATE_NAME
* ST_ABBREV

**Comment by ansell** [comment]
I deleted the layer and uploaded it again with the same result. It is now at:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10871

**Comment by ansell** [comment]
GeoTools rendered the following outline PNG successfully from the layer that failed to be uploaded:

![complete_comm_electoral](https://cloud.githubusercontent.com/assets/82365/16934450/b7703506-4d99-11e6-8677-0d40c520d134.png)

The expected field empty/non-empty/unique counts for the layer (found using GeoTools) are:

![screen shot 2016-07-19 at 10 16 14 am](https://cloud.githubusercontent.com/assets/82365/16934478/f0d0822e-4d99-11e6-9f60-85aa0db8deff.png)

**Comment by ansell** [comment]
The rendered map looks visibly very similar to that provided by the AEC:

http://aec.gov.au/profiles/files/aec-boundary-map-2016.pdf

**Comment by adam-collins** [comment]
Detect unloaded or error on loading a Layer. Display this and restrict field creation page accordingly.
