### ISSUE TITLE
Fix blocked tasks and support Postgis 3.0

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-service#192]
1, Fix bugs of task execution:
   This part of code is designed to terminate a task running more than 10 hours.  However the bug  made the termination process failed, either triggered by system automatically or manually
 
2, Upgrade docker container for dev to Postgres 12 + 3.0, including Layerstore upgrades to support Postgis 3.0  . Related to https://github.com/AtlasOfLivingAustralia/layers-store/issues/16

**Comment by qifeng-bai** [comment]
How to test:

1, Postgis 3.0 updates:
Goto spatial-test.ala.org.au -> tools -> Compare points -> Add point ->  Add Point -> Click 'Compare' 
Results should be displayed on the left panel

**Comment by patkyn** [comment]
Test passed
