### ISSUE TITLE
ClassNotFoundException for Ivy FileUtil in ManageLayersController

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#2]
Receiving a ClassNotFoundException for an Ivy class while using the ManageLayersController to upload ZIP files containing layers. Ivy may not be on the runtime classpath.

<img width="1131" alt="screen shot 2016-04-21 at 9 07 42 am" src="https://cloud.githubusercontent.com/assets/82365/14693252/9206b4e6-07a0-11e6-8a3d-2e8f9cded9a5.png">

**Comment by adam-collins** [comment]
Should be fixed now.

**Comment by ansell** [comment]
Thanks, just uploaded another file and it transitioned smoothly to the next tab without the error.
