### ISSUE TITLE
Improve tasks page usability

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#20]
After uploading some layers and creating fields from the new layer, there are sometimes data quality issues found, while the TabulationCreateOne tasks are running. Currently, the 150 or so TabulationCreateOne tasks must be allowed the complete (taking about 2-3 hours) before experimenting again. It would be very useful to have the ability to cancel all tasks in the queue to allow experimenting with different versions of a layer in a day.

**Comment by adam-collins** [comment]
add cancel task, filtering, sorting, paging and review auth requirements.
