### ISSUE TITLE
Role_admin may be refused to access APIs due to 'expired' cookie

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/spatial-service#204]
A signed role_admin or other roles may encounter 'Access denied' issues:

`You do not have permission to access this link. Please sign in with another account.` 

Users have to sign out / in again, and tick 'remember me' checkbox to refresh cookie

@nickdos and I have reviewed and tested code and there is no bugs and working on Spatial-test

@nickdos thinks we need to add some API endpoints to  the config and let Auth check the cookie

security.cas.uriFilterPattern	[/alaAdmin/?.*]
security.cas.authenticateOnlyIfLoggedInFilterPattern	[/]

**Comment by nickdos** [comment]
The explicit paths for those pages need to be added to the `security.cas.uriFilterPattern` array value.

E.g. `security.cas.uriFilterPattern = ["/alaAdmin/*/", "/tasks/*", "/manageLayers/*", "/intersect/*", "/admin/*"]` there might be other paths needed... note it is not a regex but a java classpath pattern.
