### ISSUE TITLE
Spatial - Upgrade to Grails 5 + Gradle 7 + Improvements

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/spatial-service#218]
- [x] Refactoring of task queue to remove slave instances.
- [x] Removal of  layer store
- [x]  Domain object from layer store to local/domain object
- [x]  20+ Open API annotation are now available through gateway (todo: @sughics  to upload )
- [x] Java to Groovy - Code Cleanup
- [x] Upgrade to grails 5
- [x] Upgrade to grade 7
- [x] Security plugin update to be compatible with Cognito

**Comment by sat01a** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/tree/refactor-in-progress

**Comment by sat01a** [comment]
Ready for review

**Comment by adam-collins** [comment]
Still waiting for biocollect.
