### ISSUE TITLE
Offer a progress monitor for long running tasks

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#22]
For tasks where it is possible to estimate the number of internal actions that are required, it would be useful to know whether they are progressing or whether they have stalled, just from reviewing the task list over time. In particular, when the Resolution 0.1/0.5 tasks are taking a long time, it would be useful to know whether they are actually still performing actions or whether they have silently stopped working, or whether they are progressing, but very slowly.

**Comment by adam-collins** [comment]
Refer to AtlasOfLivingAustralia/spatial-service#20
