### ISSUE TITLE
Some layer creations are put in the task queue but never triggered

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#26]
The following layer seems to have been uploaded correctly and I entered all of the metadata for it, but the LayerCreation task for it is staying in the queue and not being triggered:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10873

<img width="757" alt="screen shot 2016-07-22 at 9 10 24 am" src="https://cloud.githubusercontent.com/assets/82365/17041820/377a3a36-4fec-11e6-932c-44c44b481554.png">

**Comment by adam-collins** [comment]
Refer to AtlasOfLivingAustralia/spatial-service#20
