### ISSUE TITLE
Localise times given in the task list

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#27]
The times in the task list look like they are UTC times. It would be simpler to visualise the timelines if they were in local time. See screenshot below for something I know was triggered about 9:06 am today but seems to say last night due to timezone differences.

<img width="757" alt="screen shot 2016-07-22 at 9 10 24 am" src="https://cloud.githubusercontent.com/assets/82365/17041859/81efcdba-4fec-11e6-9d3a-00e473e2edd4.png">

**Comment by adam-collins** [comment]
This is an issue with all AWS servers in use and will be addressed elsewhere.
