### ISSUE TITLE
A recent change may be displaying "requestedId" incorrectly

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#28]
I am trying to create two different fields from a single layer and changed the requestedId to make the two fields unique. However, when viewing the fields, they do not appear to be unique, with both having the value "cl10873":

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10873

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl110873

This behaviour may be fairly recent, as I have been creating multiple fields for various layers recently and haven't noticed this before.

The task list for when the fields are created later today seems to be correct, so looks to just be a display issue.

**Comment by adam-collins** [comment]
Review default field id generation, they are getting too long.

**Comment by ansell** [comment]
The requested ID fields are now unique, so closing this issue. Follow up about the extra cl prefix in issue #52
