### ISSUE TITLE
Add date time of loaded layers.

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-service#3]

**Comment by Tasilee** [comment]
This field is vital when we need to report to users on what's new. This field should be added to http://spatial.ala.org.au/layers so it can be used for sorting. It should be possible to scan the prior issues for when the Load Layer issue was closed and use that date?

**Comment by adam-collins** [comment]
This will require work in layers-store

**Comment by adam-collins** [comment]
Date information is now on prod and test. 

Next this needs to be added to pages that list layers and fields.
