### ISSUE TITLE
TabulationCreateOne between two fields in one layer can be slow

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#31]
TabulationCreateOne between two fields in one layer, which should be able to have significant optimisations, can be slow currently.

The task that most visibly highlights this has been running for a month now and as there is no progress indicator, it is difficult to say when it will complete.

http://spatial-test.ala.org.au/spatial-service/tasks/show/341727

In that case, there are two essential attributes for the Ecological Communities of National Environmental Signficance (ECNES) layer, the name, and the signficance, so they are loaded as two separate fields of the same layer. I have noticed slowdowns in the tabulation of multiple fields of the same layer in the past, but this is the first time it has taken this long to complete.

In particular, in this case, it has left only three workers (spatial-test being setup with 4 workers in total) able to deal with the ~1300 tasks that have been scheduled since that time (many of those ~1300 tasks are related to tabulation tasks that just keep being created and are not incremental, as described in issue #30).

**Comment by adam-collins** [comment]
slow is expected.
