### ISSUE TITLE
Scalability of workers

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#33]
I am not sure if there is currently any background support for scaling up the number of workers, but it would be ideal if there was the ability to bring up temporary computing power to deal with periods when more, (or complex) layers are being uploaded to reduce lags and reduce interruption to workflows.

**Comment by adam-collins** [comment]
Additional workers is built in, i.e. additional servers to handle the additional workload.

Work on AtlasOfLivingAustralia/spatial-service#18 and AtlasOfLivingAustralia/spatial-service#20 should assist in the shorter term.
