### ISSUE TITLE
Creating two layers simultaneously fails

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#36]
I failed to create two layers simultaneously just now. In particular, I was trying to create a layer based on a filtering of another layer to remove the null values that are reported in issue #35 with my workaround that otherwise works well. However, the second layer that I clicked "Create layer" on, after entering the metadata, failed without any error, redirecting me back to the "Create layer" page without any of the metadata entered this time, except for the autogenerated "Name" and "Display name" that were derived from the shapefile, not from my previous edits.

At worst there should have been an error displayed somewhere notifying that the system only supports a single layer being created at one time, instead of silently redirecting and removing all of the information, and at best, as expected, both layers should have been created successfully.

**Comment by adam-collins** [comment]
Add error messages related to tasks for layers to the ManageLayers pages.
