### ISSUE TITLE
Min/max dimensions very large for layer

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#37]
The following layer has very large min/max lat/long bounds which are making it difficult to use in the spatial portal due to it zooming out to its max value when focusing on features:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10899

<img width="870" alt="screen shot 2016-08-24 at 2 41 32 pm" src="https://cloud.githubusercontent.com/assets/82365/17918554/4a46ae06-6a09-11e6-9ccb-9ddeeb458b0b.png">

It seems to load okay, and it renders locally using GeoTools to the following image:

![global_dl_20140109_catchments](https://cloud.githubusercontent.com/assets/82365/17918580/9b013c8a-6a09-11e6-8a53-52b79362d0d5.png)

There is a similar issue with the unfiltered version of that layer:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10898

That also seems to render properly locally using GeoTools and in the spatial portal, but the min/max are also affecting browsing of features for it:

![global_dl_20140109](https://cloud.githubusercontent.com/assets/82365/17918593/b90d0344-6a09-11e6-8cd6-64de8108927c.png)

**Comment by adam-collins** [comment]
This is a failure in the upload to geoserver. This needs to be detected on file import.

This particular example could be assisted by supplying an EPSG code during the import process to override whatever might be wrong with the detection by geoserver.
