### ISSUE TITLE
Restore session failed

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#48]
http://spatial.ala.org.au/webportal/?ss=7CF0BDB3EF3A2CF81CC675573B3AD0D7 restored the layers to the layer list but all the associated maps were "Layer unavailable".

I'm planning to try to use this functionality for the workshop 27/9/2016

**Comment by adam-collins** [comment]
Copied the qids to the new cassandra instance. You will need to clear browser cache before reloading this session.
