### ISSUE TITLE
PDF area report fails (locks up)

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#49]
I have not been able to run a PDF area report on Redland LGA and other small spatial areas for some weeks. This is urgent.

Gets to Running> Producing PDF and locks.

**Comment by adam-collins** [comment]
Tested and working on prod. Hopefully it is enough.
- Faster biocache queries for areas on indexed layers.
- Upgraded tomcat and java compile version.
- Added additional progress information at the Production PDF stage.
- Added a test to detect PDF generation failure.

**Comment by Tasilee** [comment]
Redland worked! Small issue - progress bar largely covered
![capture](https://cloud.githubusercontent.com/assets/6656350/18818550/54cfa560-83bf-11e6-9a18-dda60ac22c3c.jpg)
