### ISSUE TITLE
Link to Layer metadata fails

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#50]
Add to Map | Layers | "Distance - to any water (weighted)"
Click on (i) for metadata
Click on More informaiton (metadat) link: http://spatial.ala.org.au/geonetwork/srv/en/metadata.show?uuid=b9a1150d-9627-449e-9629-7cda5c91bf94
Get....
![capture](https://cloud.githubusercontent.com/assets/6656350/19456890/677df73c-950f-11e6-977e-e0f8c19a946b.jpg)

**Comment by matthewandrews** [comment]
Behaving as expected now after a restart of the relevant tomcat instance (00_alaspatial).

**Comment by adam-collins** [comment]
moving geonetwork to tomcat7, having issues...
