### ISSUE TITLE
Requested ID has an extra cl prefix when editing an existing field

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#52]
See screenshot below for example of the requested ID having an extra cl prefix when editing an existing field:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10841

<img width="1082" alt="screen shot 2016-10-25 at 9 46 29 am" src="https://cloud.githubusercontent.com/assets/82365/19666879/e2920920-9a98-11e6-85cb-58f0e6dc7742.png">

**Comment by adam-collins** [comment]
Editing fields is now working.
