### ISSUE TITLE
Change header text for Scatterplot Step 4

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#58]
We have confused some scatterplot users when we changed the two dropdown boxes for the layers for the X and Y axes to the more generic  table of layers with classification, correlation etc.

To make it clearer to those who may use the top dropdown instead of the second, I suggest we replace the current text

Select 2 environmental layers 

to

Select 2 environmental layers using the lower dropdown box (search and tick), or if you have a file containing the names of the two layers to be used as X and Y in the scatterplot - use the top dropdown box.

**Comment by adam-collins** [comment]
Fixed
