### ISSUE TITLE
Tools | Scatterplot - missing explanation of colouring on layer selection table

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#63]
We appear to be missing the description of the colouring on the table for layer selection of the Scatterplot tool, i.e., we are missing the text on the left of the table-

"The colours against the layers are like traffic lights. Green implies the layer is uncorrelated to all selected layers, orange implies some correlation while red implies high correlation. As you select layers, the colours change to reflect correlation with already selected layers. For example a red layer implies high correlation with at least one selected layer while a green layer implies little or no correlation to any selected layer
 
Note: The correlations are currently based on full layer spatial extents and not any selected sub-area."

**Comment by adam-collins** [comment]
This applies to 'select-layers-directive'. See http://spatial.ala.org.au for comparison.

gLayerDistances in spApp.js is filled with the data for colouring.
