### ISSUE TITLE
Scatterplot - Box selection on scatterplot not selecting points

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#64]
Scatterplot of species (e.g., Exocarpos) - drag box over core of distribution on scatterplot, release, and after a few seconds, no points highlighted on map and no points selected in legend. Serious bug!

![capture_43](https://cloud.githubusercontent.com/assets/6656350/25421079/7a7464d2-2a9e-11e7-8c35-30463889c7c0.jpg)

**Comment by adam-collins** [comment]
There is a problem with the WMS ENV parameter sent to biocache-service.

**Comment by Tasilee** [comment]
Works in spatial-beta
