### ISSUE TITLE
Establish parameter for colour up/down for environmental layers

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#66]
From Tina Schroeder and Ryonen Butcher (April 21, 2017)

"Another point I thought I should make, although it might just be me getting confused with the colouring of the precipitation map. I am finding the colour gradient is counter intuitive, I.e. In my mind, dry areas should be red – yellow and wetter areas green then blue? So the opposite of what it is now."

This isn't the first time I have raised the need to be able to pick the most logical 'polarity' for the colour scheme for the environmental layers. If there was a way of editing the equivalent of the 'layers table', and there was a parameter, I'd be happy to review all the relevant layers and set it.

**Comment by adam-collins** [comment]
Update layer sld generation in spatial-service to include a linear legend (using min/max only). Also include a reverse of the standard sld and this linear sld.

Update spatial-hub to allow selection of other valid slds for a layer.
