### ISSUE TITLE
Export of derrived layers

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#68]
I have had a number of request for exports of derived layers that we calculate monthly (which we 'own' so can release)-

Occurrence density
Species richness
Endemicity 
Shannon diversity

Likewise, it would be useful to be able to export the grids from Tools | points to Grid

Given many are wanting some batch style processing, a web service or two would be wonderful (f, fq support obviously on Point to Grid).

**Comment by adam-collins** [comment]
Add task scheduling to spatial-service.

Add DOI for these layers.

Make available at downloads.ala.org.au when generated.

**Comment by Tasilee** [comment]
This appears related to #112

**Comment by Tasilee** [comment]
Duplicate of #112
