### ISSUE TITLE
New SP: MaxEnt tweaks needed

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#69]
Step 2: test percentage, should read "Percentage of records used for testing model?" with a default of 20% (don't use fractions if we are talking percentages).
Step 3: Skip - just do it anyway. Don't ask.
Step 6: ditto - just do it anyway. (This relates to Step 2 BTW)
Step 7: nice, but suggest "0.01 decimal degrees" etc as people won't know the units. Are we in a position now to use kms or decimal degrees? **If so, we should default to kms**.

**Comment by adam-collins** [comment]
The changes can be made using spatial-hub's view-config.json

**Comment by sbearcsiro** [comment]
@Tasilee could you clarify which options Steps 3 and 6 in the above refer to?  I've assumed jackknife and responsecurves as they're boolean properties but obviously I'm just taking a shot in the dark here.

**Comment by Tasilee** [comment]
I'll step through the SP wizard

Step 1 - Area - no change
Step 2 - Taxa - no change
Step 3 - Environmental l layers - no change
Step 4 - MaxEnt options

Default (selected) "Create response curves"
Default (selected) "Do Jacknife to measure variable importance"
  Default to 20% for Jacknife
"Make pictures of predictions" is hidden and turned off as we map the probabilities
Feature selection (one of - if possible, if not hide and use default)-
  Linear features - unselected
  Quadradic features - unselected
  Product features - unselected 
  Threshold features - unselected
  Hinge features - unselected
  Auto features - SELECTED (default)

Users have also asked if a set of (optional) background points (absences) could be input - and this for us would be a separate points layer. But I can't see how this is handled in the Windows version I am looking at.
  
PS: Maxent latest is 3.4.1

**Comment by Tasilee** [comment]
Discussed options with the BCCVL guys and figure we keep it simple

Don't worry about feature selection (as anticipated) but the other options as above.
