### ISSUE TITLE
Replace all facet labels with the EXACT Darwin Core Term

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#71]
It is frustrating for those looking for Darwin Core terms to see a different label used by the ALA, for example in the SP legend facets.

We MUST replace all exposed labels that map to an explicit Darwin Core term with those terms, as specified at http://rs.tdwg.org/dwc/terms/index.htm#establishmentMeans. 

e.g., we expose "occurrenceStatus" as "Presence/Absence" - a serious embarrasment.

Rollovers would be nice that linked to the DwC definitions (if they are there, why not use them?).

**Comment by adam-collins** [comment]
http://biocache.ala.org.au/ws/index/fields is available for mapping between the SOLR field name and 'dwcTerm' instead of 'description'
