### ISSUE TITLE
Tabulation - using wrong classification

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/spatial-service#83]
Noted when cross-tabulating States and Territories vs CAPAD teerestrian 2014 - it reports each reserve instead of each reserve type (classification) e..g, National parks, IPAs, etc. The former is of far less use, but probably should be retained as a non-default option

**Comment by ansell** [comment]
Would a new field for CAPAD 2014 on reserve type in addition to the one for reserve name, which some users will find useful, meet the criteria for fixing this issue?

**Comment by Tasilee** [comment]
Yes

**Comment by nickdos** [comment]
@adam-collins please link commit, for code review

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/spatial-service/commit/050599a6df6e13b5ce093cf417a426f107fd4708
