### ISSUE TITLE
View in spatial portal link for layers is broken

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#85]
The ``View in spatial portal`` link on the spatial-service delivered ``/layers/view/more/`` doesn't seem to work with the current spatial-hub. Not sure where the issue should be created, as spatial-beta also links to ``spatial.ala.org.au``

Example page is:

``https://spatial-beta.ala.org.au/ws/layers/view/more/psma_electoral``

Example link is the following, which doesn't work when replacing spatial with spatial-beta:

``http://spatial.ala.org.au/?layers=psma_electoral``

**Comment by Tasilee** [comment]
http://spatial.ala.org.au/webportal//?layers=psma_electoral seems to work from https://spatial-beta.ala.org.au/ws/layers/view/more/psma_electoral

**Comment by ansell** [comment]
https://spatial-beta.ala.org.au/ws/layers/view/more/psma_electoral still links to http://spatial.ala.org.au/?layers=psma_electoral , but the equivalent spatial-beta URL, https://spatial-beta.ala.org.au/?layers=psma_electoral now works, which means it should work after the switchover
