### ISSUE TITLE
Look into updating Geoserver-2.1.3 to a recent version

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-service#9]
The version of Geoserver being used by spatial.ala.org.au, 2.1.3, was published in 2011, and depends on Geotools-2.7.4. The current version is Geoserver-2.9.0 and contains an up to date version of Geotools-14/15.

Given the issues I have seen with uploading SHP files that the current version of Geotools can read in my own code, it may be useful to update Geoserver to a recent version.

http://spatial.ala.org.au/geoserver/web/?wicket:bookmarkablePage=:org.geoserver.web.AboutGeoServerPage

**Comment by adam-collins** [comment]
Java on ala-maps updated and geoserver can now be deployed. This is required for spatial-service. 

Also update tomcat to a recent version.

- Install side by side geoserver and reimport all layers, including styles, into the new geoserver.
- test with spatial-service and alaspatial (existing analysis services) to ensure both can deploy layers to the upgraded geoserver.

**Comment by adam-collins** [comment]
updated prod with geoserver 2.9.1
