### ISSUE TITLE
Threatened species counts in area report

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-service#99]
I'm reporting this for the current prod system and assuming its the same in the new spatial service (close if not the case). (@Tasilee flagging for comment as well)

If viewing a suburb in Canberra, e.g. "narrabundah" via "add to map" -> "area" -> gazatteer polygon -> "View area report for Deakin", you get a "Threatened species count" that is way too high. John  has commented on this a few times now. 

```
Number of species | 159
Number of species - spatially valid only | 151
Threatened Species | 90

```
Looking at that last list, I see "Magpie Lark" (_Grallina cyanoleuca_) in there.

Checking all the "threatened" lists in the [specieslist-webapp](https://lists.ala.org.au), I could only find that species in these two:

https://lists.ala.org.au/speciesListItem/list/dr651
https://lists.ala.org.au/speciesListItem/list/dr652

So two issues here:

1. We are including threatened species lists from the wrong jurisdiction (ACT & national list should be used in this case but NT and Vic lists should NOT be). Species can be threatened in one state but not another.

2. Those 2 list contains species of "least concern" (they are really conservation status lists NOT threatened species lists) and those should either be filtered out in service or we should have a separate list that only contains "threatened" species and not just any "conservation status" entries.

**Comment by Tasilee** [comment]
The logic of both 'Threatened' (a catch-all for any conservation status) and 'Invasive' (a catch-all for any invasive status ) is the same. If a species occurring in the area has been flagged as any form of 'threatened' anywhere, it is flagged. The missing bit (that was I thought in the species list in the area report) was the jurisdiction/s where the flag was set.

Basically, the logic was that a false positive was better to ignore than a false negative.

**Comment by nickdos** [comment]
Clicking on area report line:

> Number of species  43  [ List ]

gives the following data:

```
LSID | Scientific Name | Taxon Concept | Taxon Rank | Kingdom | Phylum | Class | Order | Family | Genus | Vernacular Name | Number of records
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Acanthiza (Acanthiza)   pusilla\|urn:lsid:biodiversity.org.au:afd.taxon:fd9e6685-8b56-4cfe-8da6-3d96a6b6de2c\|Brown   Thornbill\|Animalia\|Acanthizidae | Acanthiza (Acanthiza) pusilla | (Shaw, 1790) | species | ANIMALIA | CHORDATA | AVES | PASSERIFORMES | ACANTHIZIDAE | Acanthiza | Brown Thornbill | 1
Acanthorhynchus   tenuirostris\|urn:lsid:biodiversity.org.au:afd.taxon:516cb176-5df5-4e42-a016-b7a2167d24f0\|Eastern   Spinebill\|Animalia\|Meliphagidae | Acanthorhynchus tenuirostris | (Latham, 1801) | species | ANIMALIA | CHORDATA | AVES | PASSERIFORMES | MELIPHAGIDAE | Acanthorhynchus | Eastern Spinebill | 3
Alisterus   scapularis\|urn:lsid:biodiversity.org.au:afd.taxon:3aca9928-daf5-416d-a343-60e194b2c2c2\|Australian   King-parrot\|Animalia\|Psittacidae | Alisterus scapularis | (Lichtenstein, 1816) | species | ANIMALIA | CHORDATA | AVES | PSITTACIFORMES | PSITTACIDAE | Alisterus | Australian King-Parrot | 5
Anas (Anas)   superciliosa\|urn:lsid:biodiversity.org.au:afd.taxon:da8a156f-95e2-4fcb-a6e7-52721705a70c\|Pacific   Black Duck\|Animalia\|Anatidae | Anas (Anas) superciliosa | Gmelin, 1789 | species | ANIMALIA | CHORDATA | AVES | ANSERIFORMES | ANATIDAE | Anas | Pacific Black Duck | 2
```

No `conservation status` values - which I was expecting as well @Tasilee

**Comment by ansell** [comment]
Biocache-store may be storing enough information in a JSON blob in Cassandra to disambiguate between listUids and regions for a given species based on this code snippet: https://github.com/AtlasOfLivingAustralia/biocache-store/blob/eb392a70099c212caa8bb48c17a5563beef59cf3/src/main/scala/au/org/ala/biocache/load/TaxonProfileLoader.scala#L181

**Comment by nickdos** [comment]
I think we need to restrict the threatened list to species from the jurisdictions that intersect the area being searched. False positives in this case are simply wrong and help propagate the ALA data quality myth, out there. 

The states determine the threatened species lists and they give that data to us, quid pro quo, we need to accurately reflect that data in the ALA. There is no need to guess here - we have the correct data, so we should use it. 

The basic workflow should be:

- calculate a bounds for the area in question (area report)
- determine which states intersect the bounds
- only include those state conservation lists in the threatened area report output (plus any national EPBC lists)

**Comment by Tasilee** [comment]
I (strongly) disagree, as an ecologist. We have an issue with the OLD SP (a bug that may not get fixed unless it is simple) but the new SP is doing what I had intended - that the LIST that a 'threatened' or 'invasive' species came from IS listed in the species list associated with the report.

The key issue to me is that 'threatened' (as a term covering any conservation listing) relates directly to conservation management.  If I am an ecologist, or a conservation manager I'm primarily keen to see that species are conserved. IF I do an area report and I get a species that is listed somewhere as 'threatened', even if it is NOT threatened in the area, I am very interested. Why? The area of interest is a type of refuge for that species. It may well represent a gene pool for re-establishing a threatened species within its home or 'threatened range'. If I have a lot of 'threatened' species in my area, and yet they are not listed for that area, I see that as a truly wonderful thing!

This strategy only works if the LIST that flagged the species is up front.

I would be open for an option (opt out) that restricted the listed species to those within the area jurisdiction. You can achieve this by filtering the exported list.
